### ISSUE TITLE
Es imprescindible que los Scripts de Base de Datos en postgres

### ISSUE THREAD

**Issue by carlosisotoa** [PROYECTOAUTANA/AUTANA#3]
# Scripts  de   BD

Es imprescindible que los Scripts para la creación de la Base de datos, tablas y relaciones se encuentren en este repositorio, Se debe **mantener actualizado** de manera que corresponda con el código. Sugiero que realice en un  _archivo de texto_ con el nombre **scriptBD.txt**.

**Comment by yordyjimenez** [comment]
Ya subo el scriptBD.txt con las tablas generales!
